// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxU75QX299Gko6E0S5BvOiLL7TqL2jEU',
    appId: '1:497432373430:web:72546dd40a5adb6aa8de17',
    messagingSenderId: '497432373430',
    projectId: 'flutter-games-shashi',
    authDomain: 'flutter-games-shashi.firebaseapp.com',
    storageBucket: 'flutter-games-shashi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfUcRMYCvz3xTtYIDJ3FpD9JFoxt-Ewk',
    appId: '1:497432373430:android:3ba50b6deebf6550a8de17',
    messagingSenderId: '497432373430',
    projectId: 'flutter-games-shashi',
    storageBucket: 'flutter-games-shashi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYBP2O_-yNxaWQ4zNBFlQTp7SsVQJQe48',
    appId: '1:497432373430:ios:edb1c6018d363f77a8de17',
    messagingSenderId: '497432373430',
    projectId: 'flutter-games-shashi',
    storageBucket: 'flutter-games-shashi.appspot.com',
    iosBundleId: 'com.example.talk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYBP2O_-yNxaWQ4zNBFlQTp7SsVQJQe48',
    appId: '1:497432373430:ios:8490299b28700f47a8de17',
    messagingSenderId: '497432373430',
    projectId: 'flutter-games-shashi',
    storageBucket: 'flutter-games-shashi.appspot.com',
    iosBundleId: 'com.example.talk.RunnerTests',
  );
}
